### ISSUE TITLE
Error parsing json on 

### ISSUE THREAD

**Issue by cbolanos79** [TransbankDevelopers/transbank-sdk-ruby#50]
**Describe el bug**

Error when call to `Transbank::Webpay::Oneclick::MallInscription.finish on response to Transbank::Webpay::Oneclick::MallInscription.start`
 
**Para reproducir**

``` 
irb(main):005:0> result = Transbank::Webpay::Oneclick::MallInscription.start(user_name: "miuser", email: "miuser@domain.com", response_url: "http://return_url:3001")
=> #<Transbank::Webpay::Oneclick::MallInscriptionStartResponse:0x0000564c6ce8f9b8 @token="e5107912e80b0ec34ce7dd825b7ea15b941c61d142e0b54815aec0802c7bc027", @url_webpay="https://webpay3gint.transbank.cl/webpayserver/bp_multicode_inscription.cgi">
irb(main):006:0> Transbank::Webpay::Oneclick::MallInscription.finish(token: result.token)
Traceback (most recent call last):
       16: from bin/rails:9:in `<main>'
       15: from /host/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
       14: from /host/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
       13: from /host/bundle/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
       12: from /host/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
       11: from /host/bundle/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
       10: from /host/bundle/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<main>'
        9: from /host/bundle/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        8: from /host/bundle/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
        7: from /host/bundle/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
        6: from /host/bundle/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
        5: from (irb):6
        4: from /host/bundle/gems/transbank-sdk-1.2.0/lib/transbank/sdk/oneclick/mall/mall_inscription.rb:41:in `finish'
        3: from /host/bundle/gems/transbank-sdk-1.2.0/lib/transbank/sdk/utils/net_helper.rb:35:in `http_put'
        2: from /host/bundle/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
        1: from /host/bundle/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
JSON::GeneratorError (only generation of JSON objects or arrays allowed)
```

**Comportamiento observado**

During integration for payment gateway

**Comportamiento esperado**

It should not raise an exception parsing json, it should parse json or return an error

**Capturas de pantalla**

-

**Versiones (por favor agrega aquí la siguiente información):**

- Rails 5.0.6
- Ruby: 2.5.7p206
- Bundler: 1.17.3
- Transbank gem version: 1.2.0

**Contexto adicional**

-

**Comment by ffiebig** [comment]
Entiendo que esto ya no ocurre, voy a cerrar el issue
