### ISSUE TITLE
JSON::GeneratorError: only generation of JSON objects or arrays allowed

### ISSUE THREAD

**Issue by acortes-kz** [TransbankDevelopers/transbank-sdk-ruby#87]
Estoy obteniendo este error  `JSON::GeneratorError: only generation of JSON objects or arrays allowed` cuando quiero confirmar una transacción con este codigo `Transbank::Webpay::WebpayPlus::Transaction::commit(token: @token)`

**Versiones:**
- SDK: 1.4.0
- Ruby: 2.3.0
- Bundler: 1.17.3
- Rails: 4.2.6

Este es el error completo:

```
2.3.0 :001 > Transbank::Webpay::WebpayPlus::Transaction::commit(token: @token)
JSON::GeneratorError: only generation of JSON objects or arrays allowed
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/transbank-sdk-1.4.0/lib/transbank/sdk/utils/net_helper.rb:35:in `http_put'
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/transbank-sdk-1.4.0/lib/transbank/sdk/webpay/webpay_plus/transaction.rb:41:in `commit'
        from (irb):1
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/user/.rvm/gems/ruby-2.3.0@test-transbank/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by PapoEsteban** [comment]
Hola! 

Tuve el mismo problema y es problema de la version 1.4.0 del SDK. Actualiza tu proyecto a Rails 4.2.8 para que puedas actualizar el SDK a la version 1.4.1, donde se corrige dicha version actualizando la version de la gema json tal cual se describe en los [releases]( https://github.com/TransbankDevelopers/transbank-sdk-ruby/releases) de la gema.
<img width="596" alt="image" src="https://github.com/TransbankDevelopers/transbank-sdk-ruby/assets/138263201/45a4b529-0132-48a1-8fa0-282327909081">


Saludos!

**Comment by acortes-kz** [comment]
Gracias, funciona perfecto!
